### ISSUE TITLE
[7] "É possível ao carregar a ferramenta, não trazer última pesquisa?”

### ISSUE THREAD

**Issue by carlsontrab** [vofficebr/mapa_conectividade#1]
Atualizar configuração do Kibana/ElasticSearch para não salvar a última consulta realizada

**Comment by flaviogoncalves** [comment]
Eu fiz um teste, adicionei um filtro, retornei ao Canvas e abri de novo o painel, ele não trouxe o filtro anterior.

**Comment by flaviogoncalves** [comment]
Encerrado por inatividade, se necessário pode ser reaberto
