### ISSUE TITLE
[12] "Visualizar os tipos de backbones existentes em cada município, indicando a titularidade de cada um (operadora)”

### ISSUE THREAD

**Issue by carlsontrab** [vofficebr/mapa_conectividade#10]
Funcionalidade: Mapa de backbones

Ações:

1) Revisar permissões de acesso par a conta SETEL no ambiente de homologação.
2) Criar nova conta de acesso como desenvolvedor para uso Rafael Reis (SETEL-MCOM).

**Comment by flaviogoncalves** [comment]
![image](https://user-images.githubusercontent.com/4958202/96475059-f3401180-1209-11eb-89e7-63209ef5fdd9.png)

Enviado e-mail com a senha de acesso.  Como a conta é de desenvolvedor foi dado acesso kibana_admin.

**Comment by flaviogoncalves** [comment]
Revisar acesso na SETEL está aguardando liberação

**Comment by flaviogoncalves** [comment]
Encerrado por inatividade, pode ser reaberto se necessário
