### ISSUE TITLE
[13] "filtrar por tipo de backbone existente e principalmente filtrar por município”

### ISSUE THREAD

**Issue by carlsontrab** [vofficebr/mapa_conectividade#11]
Funcionalidade: Relatório de backbone

Ação: 

Inserir opção de consulta de municípios atendidos por tipo de backhaul de determinada prestadora.
--

**Comment by flaviogoncalves** [comment]
Tabela de Backhauls foi adicionada no painel das cidades. Assim ao consultar o município é possível vizualizar os backhauls que atendem aquele município. 

![image](https://user-images.githubusercontent.com/4958202/96470280-7f4f3a80-1204-11eb-9b97-66a908a8ee9e.png)
