### ISSUE TITLE
[23] Desenvolver: facilidade de inserir novos layers na plataforma

### ISSUE THREAD

**Issue by carlsontrab** [vofficebr/mapa_conectividade#13]
Nova funcionalidade

Ação:

Funcionalidade nova.
(i) interface Web para subir uma planilha (Código do ente, nome do ente, latitude, longitude, CEP, código setor censitário);

(ii) script ELK que consulta os dados de conectividade para os entes contidos na planilha, considerado a informação de localização fornecida;

(iii) geração de um índice ElasticSearch com os dados fornecidos, acrescidos de taxa de wifi, velocidade média, IC, presença de 2G ou 3G/4G, quantidade de operadoras, código e nome do município, código e nome (se houver) do setor censitário;

(iv) geração de um novo mapa a geolocalização dos entes, com as camadas tradicionais disponíveis
--

**Comment by flaviogoncalves** [comment]
Em andamento.  primeira versão disponível para demonstração

**Comment by flaviogoncalves** [comment]
Funcionalidade implementada
