### ISSUE TITLE
[16] "Quando clicamos na seta dupla “fit to data bounds”, mapa não está atualizando"

### ISSUE THREAD

**Issue by carlsontrab** [vofficebr/mapa_conectividade#14]
Funcionalidade: Mapas

Ação:

Atualização da versão do ELK para 7.9.x.

**Comment by flaviogoncalves** [comment]
ELK já está em 7.9.1, falta exportar e importar os índices dos mapas

**Comment by flaviogoncalves** [comment]
Mapas reindexados
