### ISSUE TITLE
Funcionalidade de Geometria das bases a serem inseridas, com referência as bases de conectividade.

### ISSUE THREAD

**Issue by carlsontrab** [vofficebr/mapa_conectividade#16]
Nova funcionalidade que complementa o item [23] do relatório de apontamentos de homologação. 

Tem por objetivo permitir a comparação entre objetos advindos de bases de dados (planilhas) externas com a base de conectividade (pontos de WiFi, backhauls, torres, trechos de rotas de fibras ópticas), respeitando os formatos de dados georreferenciados disponíveis no Elasticsearch/Kibana e os tipos de queries disponíveis sobre esses tipos de dados, abaixo relacionadas:

Formatos de dados georreferenciados disponíveis:
	geo_point
	geo_shape

Queries viáveis no Elasticsearch:
	geo_bounding_box => busca ponto dentro de um retângulo;
	geo_distance => distância entre dois pontos;
	geo_polygon =>  busca um ou mais pontos dentro de um polígono;
	geo_shape => geo-shapes => verifica se um geo_shape intercepta outro geo_shape;
	geo_shape => geo-points => verificar se geo_points interceptam um geo_shape.

**Comment by flaviogoncalves** [comment]
Apesar de ser um desejo do MCOM e possível, não há formas simples que possam ser disponibilizadas no Kibana para que os membros do MCOM ou CGEE façam este tipo de consulta. 

Abaixo mostro um exemplo de chamada de uma API que traz o código do município e município por onde passa uma fibra. Ela implementa o recurso de pesquisa geométrica, mas não há outra forma senão usar a linguagem de busca do Elasticsearch. Não há o que possa ser implantado no Kibana para simplificar o uso deste tipo de funcionalidade. No exemplo abaixo podemos ver que foi passado o ID do trecho de fibra. Para gerar o resultado que e uma matriz cod_municipio e municipio é necessário iterar todos os trechos de todos os índices. Isso é feito com um script em Python ou Java Painless.  

Dessa forma não há como implementar nenhuma funcionalidade que atenda o requisito.  O recurso disponível são as queries em formato DSL. 

GET /mapa_brasil_cidades_v1/_search
{
  "_source": ["cod_municipio","nome_municipio"],
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "filter": {
        "geo_shape": {
          "geometry": {
            "indexed_shape": {
              "index": "backbone_brfibra",
              "id" : "BRaNiHEBJJDN11UxHG-c",
              "path" : "coordinates"
            },
            "relation": "intersects"
          }
        }
      }
    }
  }
}

**Comment by flaviogoncalves** [comment]
Ficou entendido que a funcionalidade desejada é a mesma do itêm 13 adicionado:

Pontos de wifi à 10, 50 e 100m
Backhaul mais próximo com a distância
Torre de celular mais próxima com a distância
