### ISSUE TITLE
ENC: Cidades com backhaul de fibra - e-mail de 03/11/2020

### ISSUE THREAD

**Issue by carlsontrab** [vofficebr/mapa_conectividade#17]
Carga de dados complementares encaminhados sobre backhauls de fibras ópticas. E-mail com a planilha encaminhada em 03/11/2020 para Flávio.

**Comment by carlsontrab** [comment]
Essa carga tem previsão de ser feita periodicamente. Portanto, será necessária a automação do processo de ETL. Foi fechado um padrão de planilha para novos envios dos dados: UF, CÓDIGO MUNICÍPIO, NOME MUNICÍPIO, CAPACIDADE EM Gb/s, NOME PROVEDOR, CNPJ PROVEDOR. 

Uma vez carregada a planilha, deverá ser ajustado dos indicadores relevantes: IC e status_fibra.

**Comment by flaviogoncalves** [comment]
Tarefa concluída.
