### ISSUE TITLE
Retirar duplicidade de campo "ic" e "indice_conectividade"

### ISSUE THREAD

**Issue by carlsontrab** [vofficebr/mapa_conectividade#19]
Foi detectado nos índices abaixo a existência dos campos "ic" e "indice_conectividade". Verificar se é uma redundância, e caso positivo retirar (apagar) o campo "indice_conectividade".

	mapa* 
	mapa_brasil_cidades
	mapa_brasil_distritos

**Comment by samuelamico** [comment]
Corrigido.

**Comment by flaviogoncalves** [comment]
Marca no github como corrigido e closed, por favor.

Att,

Flavio E. Goncalves
Diretor Presidente
Grupo V.Office
Linkedin: www.linkedin.com/in/flavioegoncalves

** Se deseja marcar uma reunião, você pode evitar a troca de e-mails. Para
agendar, verifique um horário disponível e agende diretamente através da
minha agenda. https://calendly.com/flavio-goncalves/30min



Em qua., 11 de nov. de 2020 às 09:36, Samuel Amico <notifications@github.com>
escreveu:
