### ISSUE TITLE
[6] Plotar mapa dos municípios que possuem backbone, com possibilidade de agregar layer de municípios que possuem 3G e 4G, índice de conectividade, mapa de wi-fi, etc.

### ISSUE THREAD

**Issue by flaviogoncalves** [vofficebr/mapa_conectividade#2]
No mapa das cidades não existe hoje uma camada que mostre as torres de celular e se são 3G e /ou 4G.  Estas informações estão disponíveis no sistema mosaico e hoje estão presentes no sistema no índice obj_torres.  

Para reproduzir basta abrir o mapa das cidades e ver que não há uma camada refletindo o índice obj_torres. 

1 - Verificar se o índice está correto e completo

2 - Plotar no mapa das cidades observando o nível de zoom adequado.

3 - Verificar a existência dos campos uf_keyword e cod_municipio.keyword (que são chaves de busca comuns no dashboard), sem elas não é possível filtrar. 

4 - Adicionar no painel das cidades um relatório que mostre estes dados para os filtros selecionados. 

5 - Alterar no ambiente de desenvolvimento. 

6 - Submeter para aprovação do Gerente de Projeto antes de transferir para produção. 

7 - Não esquecer de liberar o acesso aos índices necessários para os usuários do MCOM.

**Comment by samuelamico** [comment]
Adicionado no painel das cidades (ambiente de Desenvolvimento) nova camada.

**Comment by flaviogoncalves** [comment]
Esta tabela foi adicionada ao painel das cidades.

![image](https://user-images.githubusercontent.com/4958202/96477009-621e6a00-120c-11eb-9277-cd73ccc72348.png)

As torres foram adicionadas ao mapa das cidades.  No kibana 7.9 existe uma funcionalidade nova que agrega os pontos quando a quantidade é maior que 10000 ao invés de parar. Abaixo o mapa agregado

![image](https://user-images.githubusercontent.com/4958202/96477354-c5100100-120c-11eb-9597-2e9552d57dcf.png)

Abaixo o mapa aberto. 

![image](https://user-images.githubusercontent.com/4958202/96477500-f5579f80-120c-11eb-9055-2543aa044ccb.png)
