### ISSUE TITLE
Mapeamento de internet em destinos turísticos

### ISSUE THREAD

**Issue by carlsontrab** [vofficebr/mapa_conectividade#20]
Solicitação de mapeamento de situação de conectividade em municípios encaminhados no e-mail "ENC: Mapeamento de internet em destinos turísticos" de segunda-feira, 7 de dezembro de 2020 15:13, enviado pelo Rafael/SETEL/MCOM e reencaminhado à VOffice (Flávio), com a planilha anexada.

**Comment by rafacreis** [comment]
Pessoal, foi enviado arquivo para verificação / combinação de possível informações de conectividade.
A demanda é: existe conectividade nesses municípios? Presença de backhaul? Qual tipo?Presença de pontos wifi? A qualquer distância? Presença de FO cortando o município? tem GESAC?

GRATO

**Comment by flaviogoncalves** [comment]
Foi criado um índice chamado mcom-cidades_turísticas com as informações solicitadas.  Todos os índices começando com mcom, tem acesso pela conta mctic.
