### ISSUE TITLE
Base de Dados GESAC

### ISSUE THREAD

**Issue by carlsontrab** [vofficebr/mapa_conectividade#22]
De: Rafael Reis <rafael.reis@mctic.gov.br>
Data: sexta-feira, 11 de dezembro de 2020 11:14
Para: Carlson Oliveira <carlson@cgee.org.br>
Cc: José Afonso Cosmo Junior <jose.afonso@mctic.gov.br>
Assunto: Base de Dados GESAC

Prezado Carlson,
 
Segue a base de dados mais recente do GESAC.
Solicitamos atualização na ferramenta dos mapas.
 
Grato.
 
Rafael Cardoso Reis
Coordenador de Sistemas e Monitoramento - COSMO
Coordenação Geral de Infraestrutura para Telecomunicações
Departamento de Projetos de Infraestrutura de Telecomunicações e Banda Larga
Ministério das Comunicações 
Esplanada dos Ministérios - Bloco R, CEP 70044-900 - Brasília-DF
Telefone: (61) 2027-630
Rafael.reis@mctic.gov.br

**Comment by flaviogoncalves** [comment]
Em andamento, está sendo inserida na plataforma de gestão dos ETLs,

**Comment by flaviogoncalves** [comment]
Importado, algumas linhas não tinham coordenadas ou estava com defeito (, ao in'ves de ponto)

registros importados: 10990, registros pulados por valores nulos: 1116
