### ISSUE TITLE
Mapa Rotas do programa Amazônia Integrada e Sustentável - PAIS

### ISSUE THREAD

**Issue by rafacreis** [vofficebr/mapa_conectividade#26]
Prezados,

Solicitamos o mapa, referente aos municípios em anexo, a visualização deverá conter, o cruzamento com as bases de conectividade, com referências aos índices de presença de backhaul, tx de wi-fi, coberturas móvel, e ic, semelhante ao projeto SUDENE.

A disposição para detalhamentos.

att;

Rafael
[Municípios_Programa Amazonia Sustentavel_PAIS.xlsx](https://github.com/vofficebr/mapa_conectividade/files/6076115/Municipios_Programa.Amazonia.Sustentavel_PAIS.xlsx)

**Comment by carlsontrab** [comment]
Mapa disponível em:

https://3886e61a343a4d1ca414ff84d6034a44.us-east-1.aws.found.io:9243/app/maps/map/26fd5540-80d8-11eb-a15f-5beae0284998#?_g=(filters:!(),refreshInterval:(pause:!f,value:10000),time:(from:now-1h,to:now))&_a=(filters:!(),query:(language:kuery,query:''))

O índice utilizado é o mcom-amazonia-sustentavel a partir do qual pode-se gerar o CSV.
