### ISSUE TITLE
[3] Caso SMP - "informações sobre a presença de Serviço de Comunicação Multimídia - SCM e/ou Serviço Móvel Pessoal - SMP, não foi disponibilizada com o detalhamento solicitado”

### ISSUE THREAD

**Issue by carlsontrab** [vofficebr/mapa_conectividade#5]
Ação (acertada em reunião com MCOM):
Funcionalidade: Mapa das cidades
SMP => Será implementada camada com a atendimento 3G/4G (estações do SMP).

**Comment by flaviogoncalves** [comment]
Estações licenciadas foi adicionada ao painel das cidades.

![image](https://user-images.githubusercontent.com/4958202/96469024-23d07d00-1203-11eb-967c-414e1ab4ce06.png)
