### ISSUE TITLE
[3] Caso SMP - ITEM NOVO

### ISSUE THREAD

**Issue by carlsontrab** [vofficebr/mapa_conectividade#6]
"informações sobre a presença de Serviço de Comunicação Multimídia - SCM e/ou Serviço Móvel Pessoal - SMP, não foi disponibilizada com o detalhamento solicitado”

Funcionalidade: Mapa das cidades, relatório das cidades

Ação:

Nova fonte de dados: cobertura de atendimento das ERB (shape) advindo do sistema Mosaico / Anatel.

**Comment by flaviogoncalves** [comment]
Aguardando acesso a nova fonte de dados.

**Comment by flaviogoncalves** [comment]
Importado como obj_torres_teste
