### ISSUE TITLE
[3] - Caso SCM - ITEM NOVO

### ISSUE THREAD

**Issue by carlsontrab** [vofficebr/mapa_conectividade#7]
"informações sobre a presença de Serviço de   Comunicação Multimídia - SCM e/ou Serviço Móvel Pessoal - SMP, não foi   disponibilizada com o detalhamento solicitado”

Funcionalidade: Mapa das cidades, Relatório dos setores censitários (a ser criado em outro Issue).

Ação:

SCM => Operadoras por distrito: a Consulta de  atendimento por CEP não teve resposta das grandes operadoras. Requer novos dados SkyHook.

**Comment by flaviogoncalves** [comment]
Dados da Skyhook não serão adquiridos nesta fase
