### ISSUE TITLE
[5] "Está faltando muitos dados quando comparamos com planilha da Anatel de informações de municípios que possuem backhaul com fibra”

### ISSUE THREAD

**Issue by carlsontrab** [vofficebr/mapa_conectividade#8]
Funcionalidade: Mapa de backbones

Ação:

Associado ao possível problema de permissões no ambiente de produção / diferenças entre ambientes de produção e   desenvolvimento.

**Comment by flaviogoncalves** [comment]
Aguardando o recebimento dos novos dados de backhaul.

**Comment by carlsontrab** [comment]
Ok. O foco aqui é se os dois ambientes estão compatíveis em relação a dados e permissões dos usuários.

**Comment by flaviogoncalves** [comment]
Não recebemos até o momento acesso ao ambiente de produção. Isso impede que possamos corrigir quaisquer inconsistências.

**Comment by flaviogoncalves** [comment]
O ambiente de produção foi atualizado
